package br.com.danielsan.dscontacts.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TAG".
 */
public class Tag {

    private Long id;
    /** Not-null value. */
    private String text;
    /** Not-null value. */
    private String fieldName;

    public Tag() {
    }

    public Tag(Long id) {
        this.id = id;
    }

    public Tag(Long id, String text, String fieldName) {
        this.id = id;
        this.text = text;
        this.fieldName = fieldName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

    /** Not-null value. */
    public String getFieldName() {
        return fieldName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

}
