package br.com.danielsan.dscontacts.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WEBSITE".
 */
public class Website {

    private Long id;
    /** Not-null value. */
    private String content;
    private long contactId;

    public Website() {
    }

    public Website(Long id) {
        this.id = id;
    }

    public Website(Long id, String content, long contactId) {
        this.id = id;
        this.content = content;
        this.contactId = contactId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    public long getContactId() {
        return contactId;
    }

    public void setContactId(long contactId) {
        this.contactId = contactId;
    }

}
