package br.com.danielsan.dscontacts.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "TAG".
 */
public class Tag extends br.com.danielsan.dscontacts.dao.Tag implements Parcelable {

    public Tag() { }

    public Tag(Long id) {
        super(id);
    }

    public Tag(Long id, String text, String fieldName) {
        super(id, text, fieldName);
    }

    @Override
    public int describeContents() {
        return 3;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(this.getId());
        dest.writeString(this.getText());
        dest.writeString(this.getFieldName());
    }

    protected Tag(Parcel in) {
        this.setId(in.readLong());
        this.setText(in.readString());
        this.setFieldName(in.readString());
    }

    public static final Creator<Tag> CREATOR = new Creator<Tag>() {
        public Tag createFromParcel(Parcel source) {
            return new Tag(source);
        }
        public Tag[] newArray(int size) {
            return new Tag[size];
        }
    };
}
